<h1>Let's Build A Neural Network</h1>

<h2>Quick Python Review</h2>

<h3>Print 'Hello World'</h3>

In [1]:
print('Hello World')

Hello World


<h3>Arrays</h3>

In [2]:
myArray = ['Uno', 'Dos', 'Tres']

In [3]:
print(myArray)

['Uno', 'Dos', 'Tres']


<h3>For loops</h3>

In [4]:
for n in myArray:
    print(n)

Uno
Dos
Tres


<h3>Functions</h3>

In [5]:
def myFunction(leArray):
    for n in leArray:
        print(n)

In [6]:
myFunction(myArray)

Uno
Dos
Tres


In [7]:
myFunction([1, 2, 3])

1
2
3


In [8]:
myFunction([0.1, 0.2, 0.3])

0.1
0.2
0.3


<h2>Creating Functions and Initialising The Network</h2>

A neural network should have the following basic functions:
<ul>
    <li><b>Initialisation</b> - for defining the input, hidden, and output nodes.</li>
    <li><b>Training</b> - for refining the weights during the training process.</li>
    <li><b>Query</b> - to process an output given the input.</li>
</ul>

In [9]:
# class definition
class myNeuralNetwork:

    # initialisation
    def __init__():
        pass

    # training
    def train():
        pass

    # querying
    def query():
        pass

<h3>Initialising The Network</h3>

In [10]:
# class definition
class myNeuralNetwork:

    # initialisation
    def __init__(self, inputNodes, hiddenNodes, outputNodes, learningRate):
        # set number of nodes per layer
        self.inputNodes = inputNodes
        self.hiddenNodes = hiddenNodes
        self.outputNodes = outputNodes

        # set learning rate
        self.learningRate = learningRate

        pass

    # training
    def train():
        pass

    # querying
    def query():
        pass

In [11]:
# set number of nodes per layer
inputNodes = 3
hiddenNodes = 3
outputNodes = 3

# set learning rate
learningRate = 0.3

In [12]:
# create instance of neural network
myNetwork = myNeuralNetwork(inputNodes, hiddenNodes, outputNodes, learningRate)

<h3>Initialising Weights</h3>

<h4>Import Numpy Library</h4>

In [13]:
import numpy as np

In [14]:
np.random.rand(3, 3) - 0.5

array([[ 0.00303361,  0.02141858,  0.332328  ],
       [-0.24591873, -0.15091297, -0.21523857],
       [ 0.05706478,  0.09855197,  0.48616968]])

In [15]:
np.random.normal(0.0, pow(inputNodes, -0.5), size=(hiddenNodes, inputNodes))

array([[-0.15180167, -0.2288197 , -0.9082402 ],
       [ 0.11588923,  0.2429699 , -0.08997956],
       [ 0.21106557, -0.46745529, -0.17720931]])

<h4>Adding Weights To Our __init__ Function</h4>

In [16]:
# class definition
class myNeuralNetwork:

    # initialisation
    def __init__(self, inputNodes, hiddenNodes, outputNodes, learningRate):
        # set number of nodes per layer
        self.inputNodes = inputNodes
        self.hiddenNodes = hiddenNodes
        self.outputNodes = outputNodes

        # set learning rate
        self.learningRate = learningRate

        # link weight matrices between nodes
        self.weightsInputToHidden = numpy.random.normal(0.0, pow(inputNodes, -0.5), size=(hiddenNodes, inputNodes))
        self.weightsHiddenToOutput = numpy.random.normal(0.0, pow(hiddenNodes, -0.5), size=(outputNodes, hiddenNodes))

        pass

    # training
    def train():
        pass

    # querying
    def query():
        pass

<h3>Querying The Network</h3>

<h4>Activation Function</h4>

In [17]:
import scipy.special

In [18]:
# sigmoid function
activationFunction = lambda x: scipy.special.expit(x)

<h4>Matrix Computation Using Dot Function</h4>

In [19]:
myArray1 = ([[1, 2, 3], 
             [4, 5, 6], 
             [7, 8, 9]])
myArray1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
myArray2 = ([[1], 
             [1], 
             [1]])
myArray2

[[1], [1], [1]]

In [21]:
np.dot(myArray1, myArray2)

array([[ 6],
       [15],
       [24]])

<h4>Calculating Signals Between Layers</h4>

In [22]:
inputsList = ([[1, 2, 3], 
             [4, 5, 6], 
             [7, 8, 9]])

# convert inputs to 2D matrix
inputs = np.array(inputsList, ndmin = 2).T

In [23]:
# class definition
class myNeuralNetwork:

    # initialisation
    def __init__(self, inputNodes, hiddenNodes, outputNodes, learningRate):
        # set number of nodes per layer
        self.inputNodes = inputNodes
        self.hiddenNodes = hiddenNodes
        self.outputNodes = outputNodes

        # set learning rate
        self.learningRate = learningRate

        # link weight matrices between nodes
        self.weightsInputToHidden = np.random.normal(0.0, pow(inputNodes, -0.5), size=(hiddenNodes, inputNodes))
        self.weightsHiddenToOutput = np.random.normal(0.0, pow(hiddenNodes, -0.5), size=(outputNodes, hiddenNodes))

        pass

    # training
    def train():
        pass

    # querying
    def query(self, inputs_list):
        # convert inputs to 2D matrix
        inputs = np.array(inputsList, ndmin = 2).T
        
        # compute signals into hidden layer
        hiddenInputs = np.dot(self.weightsInputToHidden, inputs)
        # compute signals from hidden layer
        hiddenOutputs = self.activationFunction(hiddenInputs)

        # compute signals into output layer
        finalInputs = np.dot(self.weightsHiddenToOutput, hiddenOutputs)
        # compute signals from output layer
        finalOutputs = selfactivationFunction(finalInputs)
        
        pass